### ISSUE TITLE
Rules to update nick

### ISSUE THREAD

**Issue by Systerr** [Tonium-io/tonium-frontend#33]

**Comment by vatic555** [comment]
Now I propose to do it as follows:
At the first stage, give only unique nicknames more than 8 characters with a mandatory capital letter as min 1, in the Latin alphabet, with a number (s) and a special symbol.
Then we will think over and start selling beautiful nicknames (with smaller symbols, according to the dictionary, without numbers and special symbols).

**Comment by vatic555** [comment]
Canceled, as a decentralized mechanism will be implemented via DeNS
