### ISSUE TITLE
Add difference text

### ISSUE THREAD

**Issue by Systerr** [Tonium-io/tonium-frontend#34]
![image](https://user-images.githubusercontent.com/1553394/126260563-233d869a-d2ae-47cf-8335-d619f7703567.png)

@vatic555  please provide text and the ask Roma to implement

**Comment by vatic555** [comment]
When a file is placed in the blockchain, it is stored distributed and remains immutable and non-removable. In this case, the file is stored completely in the NFT. However, the fee for uploading a file may be higher. 
In IPFS, data is stored locally in the p2p system and transmitted to other users via the protocol. When uploading to IPFS, only the link to the file and the hash are placed into the NFT
