### ISSUE TITLE
After I mint the token, 2 errors occur

### ISSUE THREAD

**Issue by vatic555** [Tonium-io/tonium-frontend#44]
http://joxi.ru/krDJ7BNTgx5Pl2
1. The wrong collection name is displayed (if you go back to the list of collections and go back inside the collection, then the correct name is displayed). The error occurs only after creating a new token.
2. Also after creating a new token - it is not displayed in the collection. You either have to press F5 or go back to the list of collections and back.
We need to fix it.

**Comment by shaw12** [comment]
Both issue have been resolved.
